# Sample .travis.yml for R projects

language: r
dist: xenial
cache:
  - $HOME/.ccache
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      r: devel
    - os: linux
      dist: trusty
      sudo: false
      r: release
    - os: linux
      dist: trusty
      sudo: false
      r: oldrel
    - os: osx
      r: release

addons:
  apt:
    packages:
      - ccache
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - protobuf-compiler
      - valgrind
      - libjq-dev
      - netcdf-bin
  brew_packages:
      - udunits
      - gdal

branches:
  only:
    - master
    - develop
    
before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/xenial/latest'))" >> ~/.Rprofile.site; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
       ')'))" >> ~/.Rprofile.site; fi
    
script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check mxmaps*tar.gz
  - travis_wait 50 Rscript -e "tryCatch({install.packages(c('remotes', 'sf', 'rgdal', 'rgeos', 'geojsonio', 'ggrepel', 'leaflet', 'jsonlite'));remotes::install_github('r-lib/pkgdown');remotes::install_github('diegovalle/mxmaps');remotes::install_github('Eflores89/inegiR');pkgdown::build_site()}, error = function(e) {quit(status=1)})"

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - cran/survival

after_success:
  - travis_wait 40 Rscript -e 'covr::coveralls()'
